import type { Project } from '../types'

export const PROJECTS: Array<Project> = [
  {
    id: 'pc2026',
    title: 'Pomodoro Claw',
    category: 'PWA',
    description:
      'Productivity timer combining Pomodoro technique with claw machine gamification mechanics.',
    image: '/projects/pomodoro-claw.png',
    tags: ['PWA', 'TypeScript', 'Netlify', 'Google Ai Studio', 'OnGoing'],
    link: 'https://pomodoro-claw.netlify.app',
    year: '2026',
  },
  {
    id: 'ch1',
    title: 'Breath Natural',
    category: 'Next.js',
    description: 'Premium e-commerce for indoor plants with fluid UX.',
    image: '/projects/breath-natural.png',
    tags: ['Next.js 15', 'Framer Motion', 'Tailwind', 'Study', 'OnGoing'],
    link: 'https://breath-natural-nextjs-chronicles.netlify.app',
    year: '2025',
  },
  {
    id: 'f1',
    title: 'Edifício Canadá',
    category: 'Next.js',
    description: 'Luxury real estate landing page with Lighthouse 90+.',
    image: '/projects/edificio-canada-rvone-freelance.png',
    tags: ['Next.js 13', 'SSR', 'SEO', 'Freelance', 'Completed'],
    link: 'https://edificio-canada-freelance-langing.netlify.app/',
    year: '2025',
  },
  {
    id: 'ch2',
    title: 'Food Hut',
    category: 'Angular',
    description: 'Restaurant landing page with mobile-first PWA capabilities.',
    image: '/projects/food-hut.png',
    tags: ['Angular', 'PWA', 'Tailwind', 'Study', 'OnGoing'],
    link: 'https://food-hut-angular-chronicles-1.netlify.app/',
    year: '2025',
  },
  {
    id: 'ch3',
    title: 'Savana Nuxt',
    category: 'Vue',
    description: 'Multi-language e-commerce with global state management.',
    image: '/projects/savana.webp',
    tags: ['Nuxt 3', 'Pinia', 'i18n', 'Study', 'OnGoing'],
    link: 'https://savana-nuxtjs-chronicles-part-1.netlify.app/en',
    year: '2025',
  },
  {
    id: 'ch4',
    title: 'Persona NextJS',
    category: 'Next.js',
    description: 'Elite engineering portfolio showcasing 4+ years of expertise.',
    image: '/projects/persona.png',
    tags: ['Next.js', 'Lighthouse', 'PWA', 'Study', 'Completed'],
    link: 'https://persona-nextjs-chronicles-2.netlify.app',
    year: '2025',
  },
  {
    id: 'ch5',
    title: 'Zenith Node',
    category: 'Node.js',
    description: 'Fundamental backend informational site with native HTTP.',
    image: '/projects/zenith-node-chronicles-part-1.png',
    tags: ['Node.js', 'FS', 'HTTP', 'Study', 'Completed'],
    link: 'https://replit.com/@ricardo564/zenith-node-chronicles-part-1',
    year: '2025',
  },
  // {
  //   id: 'o2',
  //   title: 'Lembre de Mim',
  //   category: 'Python',
  //   description: 'Visual Novel game combining storytelling and technical implementation.',
  //   image: '/projects/lembre-de-min.png',
  //   tags: ['RenPy', 'Python', 'Game', 'Study', 'Completed', 'With Friends'],
  //   link: 'https://lembredemin.netlify.app/',
  //   year: '2025',
  // },
  // {
  //   id: 'o1',
  //   title: 'Cigana Lila',
  //   category: 'Astro',
  //   description: 'Spiritual services website with WhatsApp integration.',
  //   image: '',
  //   comingSoon: true,
  //   tags: ['Astro', 'TypeScript', 'Netlify', 'Freelance', 'OnGoing'],
  //   link: 'https://cigana-lila.netlify.app/',
  //   year: '2025',
  // },
]

export const USER_PHOTO =
  '/images/ricardo-camilo-programador-frontend-web-developer-frontend-engineer-software-engineer-web-developer-vuejs-vue-reactjs-react-javascript-typescript.png'
