import type { Project } from '../types'

export const PROJECTS: Array<Project> = [
  {
    id: 'c1',
    title: 'Labi9.com',
    year: '2024',
    category: 'Qwik',
    description: 'Corporate website for software development leader.',
    image: '/projects/labi9.png',
    tags: ['Qwik', 'PWA', 'Tailwind'],
    link: 'https://web.archive.org/web/20250116083000/https://labi9.com/',
  },
  {
    id: 'c2',
    title: 'Loor.vc',
    year: '2024',
    category: 'Astro',
    description: 'Connecting investors with high-potential startups.',
    image: '/projects/loor.png',
    tags: ['Astro', 'Vue', 'Tailwind'],
    link: 'https://web.archive.org/web/20250108164137/https://loor.vc/',
  },
  {
    id: 'c3',
    title: 'Loor Dashboard',
    year: '2024',
    category: 'React',
    description: 'Professional-grade investment management platform.',
    image: '/projects/loor-admin.png',
    tags: ['React', 'Redux', 'Vite'],
    link: 'https://web.archive.org/web/20250108164137/https://loor.vc/',
  },
  {
    id: 'c4',
    title: 'Global Liberty Bank',
    year: '2024',
    category: 'Astro/Vue',
    description: 'Modern banking interface with elegant financial sector aesthetics.',
    image: '/projects/glbk.png',
    tags: ['Astro', 'Vue.js', 'Tailwind'],
    link: 'https://web.archive.org/web/20250415133508/https://www.glbk.com.br/',
  },
  {
    id: 'c5',
    title: 'Tippbank',
    year: '2024',
    category: 'Astro/Vue',
    description: 'Financial planning and payment solutions platform.',
    image: '/projects/tippbank.png',
    tags: ['Astro', 'Vue', 'Tailwind'],
    link: 'https://web.archive.org/web/20240324074834/https://tippbank.com.br/',
  },
  {
    id: 'f1',
    title: 'Edifício Canadá',
    category: 'Next.js',
    description: 'Luxury real estate landing page with Lighthouse 90+.',
    image: '/projects/edificio-canada-rvone-freelance.png',
    tags: ['Next.js 13', 'SSR', 'SEO'],
    link: 'https://edificio-canada-freelance-langing.netlify.app/',
  },
  {
    id: 'ch1',
    title: 'Breath Natural',
    category: 'Next.js',
    description: 'Premium e-commerce for indoor plants with fluid UX.',
    image: '/projects/breath-natural.png',
    tags: ['Next.js 15', 'Framer Motion', 'Tailwind'],
    link: 'https://breath-natural-nextjs-chronicles.netlify.app',
  },
  {
    id: 'ch2',
    title: 'Food Hut',
    category: 'Angular',
    description: 'Restaurant landing page with mobile-first PWA capabilities.',
    image: '/projects/food-hut.png',
    tags: ['Angular', 'PWA', 'Tailwind'],
    link: 'https://food-hut-angular-chronicles-1.netlify.app/',
  },
  {
    id: 'ch3',
    title: 'Savana Nuxt',
    category: 'Vue',
    description: 'Multi-language e-commerce with global state management.',
    image: '/projects/savana.webp',
    tags: ['Nuxt 3', 'Pinia', 'i18n'],
    link: 'https://savana-nuxtjs-chronicles-part-1.netlify.app/en',
  },
  {
    id: 'ch4',
    title: 'Persona NextJS',
    category: 'Next.js',
    description: 'Elite engineering portfolio showcasing 4+ years of expertise.',
    image: '/projects/persona.png',
    tags: ['Next.js', 'Lighthouse', 'PWA'],
    link: 'https://persona-nextjs-chronicles-2.netlify.app',
  },
  {
    id: 'ch5',
    title: 'Zenith Node',
    category: 'Node.js',
    description: 'Fundamental backend informational site with native HTTP.',
    image: '/projects/zenith-node-chronicles-part-1.png',
    tags: ['Node.js', 'FS', 'HTTP'],
    link: 'https://replit.com/@ricardo564/zenith-node-chronicles-part-1',
  },
  {
    id: 'o1',
    title: 'Cigana Lila',
    category: 'Astro',
    description: 'Spiritual services website with WhatsApp integration.',
    image: '',
    comingSoon: true,
    tags: ['Astro', 'TypeScript', 'Netlify'],
    link: 'https://cigana-lila.netlify.app/',
  },
  {
    id: 'o2',
    title: 'Lembre de Mim',
    category: 'Python',
    description: 'Visual Novel game combining storytelling and technical implementation.',
    image: '',
    comingSoon: true,
    tags: ['RenPy', 'Python', 'Game'],
    link: 'https://lembredemin.netlify.app/',
  },
]

export const TIMELINE = [
  {
    id: 1,
    period: 'Nov 2025 — Present',
    company: 'Consir Informática',
    role: 'Frontend Engineer',
    desc: 'Liderança técnica na modernização de sistema legado de gestão sindical para Vue.js 3 + TypeScript. Implementação de arquitetura base store com Pinia e PWA.',
    tags: ['Vue 3', 'TypeScript', 'Pinia', 'PWA'],
  },
  {
    id: 2,
    period: 'Jul 2025 — Nov 2025',
    company: 'Consir Informática',
    role: 'Pleno Frontend Engineer',
    desc: 'Engenharia de sistemas corporativos escaláveis focada em Vue.js, TypeScript e manutenção de alto nível.',
    tags: ['Vue.js', 'TypeScript', 'Enterprise'],
  },
  {
    id: 3,
    period: 'Jan 2025 — Jul 2025',
    company: 'Freelance Specialist',
    role: 'Frontend Consultant',
    desc: 'Liderança técnica em projetos de alto impacto (Itu Pneus, RvOne, Cajuscript) com foco em conversão e performance.',
    tags: ['Next.js 15', 'SEO', 'Consultancy'],
  },
  {
    id: 4,
    period: 'Oct 2021 — Dec 2024',
    company: 'Labi9 Tecnologia',
    role: 'Frontend Developer',
    desc: '3+ anos em ecossistema de fintechs. Desenvolvimento de interfaces complexas com React, Qwik e Nuxt.',
    tags: ['React', 'Nuxt', 'Fintech'],
  },
  {
    id: 5,
    period: '2019',
    company: 'SIALOG Software',
    role: 'Tech Intern',
    desc: 'Fundamentos em Ruby on Rails e JasperReports para logística.',
    tags: ['Ruby on Rails', 'Git'],
  },
]

export const USER_PHOTO =
  '/images/ricardo-camilo-programador-frontend-web-developer-frontend-engineer-software-engineer-web-developer-vuejs-vue-reactjs-react-javascript-typescript.png'
export const WHATSAPP_URL = 'https://wa.me/5514996765389'
