import type { Project } from '../types'

export const PROJECTS: Array<Project> = [
  {
    id: 'pc2026',
    title: 'Pomodoro Claw',
    category: 'PWA',
    description: 'Productivity timer combining Pomodoro technique with claw machine gamification mechanics.',
    image: '/projects/pomodoro-claw.png',
    tags: ['PWA', 'TypeScript', 'Netlify', 'Google Ai Studio', 'OnGoing'],
    link: 'https://pomodoro-claw.netlify.app',
    year: '2026',
  },
  {
    id: 'ch1',
    title: 'Breath Natural',
    category: 'Next.js',
    description: 'Premium e-commerce for indoor plants with fluid UX.',
    image: '/projects/breath-natural.png',
    tags: ['Next.js 15', 'Framer Motion', 'Tailwind', 'Study', 'OnGoing'],
    link: 'https://breath-natural-nextjs-chronicles.netlify.app',
    year: '2025',
  },
  {
    id: 'f1',
    title: 'Edifício Canadá',
    category: 'Next.js',
    description: 'Luxury real estate landing page with Lighthouse 90+.',
    image: '/projects/edificio-canada-rvone-freelance.png',
    tags: ['Next.js 13', 'SSR', 'SEO', 'Freelance', 'Completed'],
    link: 'https://edificio-canada-freelance-langing.netlify.app/',
    year: '2025',
  },
  {
    id: 'ch2',
    title: 'Food Hut',
    category: 'Angular',
    description: 'Restaurant landing page with mobile-first PWA capabilities.',
    image: '/projects/food-hut.png',
    tags: ['Angular', 'PWA', 'Tailwind', 'Study', 'OnGoing'],
    link: 'https://food-hut-angular-chronicles-1.netlify.app/',
    year: '2025',
  },
  {
    id: 'ch3',
    title: 'Savana Nuxt',
    category: 'Vue',
    description: 'Multi-language e-commerce with global state management.',
    image: '/projects/savana.webp',
    tags: ['Nuxt 3', 'Pinia', 'i18n', 'Study', 'OnGoing'],
    link: 'https://savana-nuxtjs-chronicles-part-1.netlify.app/en',
    year: '2025',
  },
  {
    id: 'ch4',
    title: 'Persona NextJS',
    category: 'Next.js',
    description: 'Elite engineering portfolio showcasing 4+ years of expertise.',
    image: '/projects/persona.png',
    tags: ['Next.js', 'Lighthouse', 'PWA', 'Study', 'Completed'],
    link: 'https://persona-nextjs-chronicles-2.netlify.app',
    year: '2025',
  },
  {
    id: 'ch5',
    title: 'Zenith Node',
    category: 'Node.js',
    description: 'Fundamental backend informational site with native HTTP.',
    image: '/projects/zenith-node-chronicles-part-1.png',
    tags: ['Node.js', 'FS', 'HTTP', 'Study', 'Completed'],
    link: 'https://replit.com/@ricardo564/zenith-node-chronicles-part-1',
    year: '2025',
  },
  {
    id: 'o2',
    title: 'Lembre de Mim',
    category: 'Python',
    description: 'Visual Novel game combining storytelling and technical implementation.',
    image: '/projects/lembre-de-min.png',
    tags: ['RenPy', 'Python', 'Game', 'Study', 'Completed', 'With Friends'],
    link: 'https://lembredemin.netlify.app/',
    year: '2025',
  },
  {
    id: 'o1',
    title: 'Cigana Lila',
    category: 'Astro',
    description: 'Spiritual services website with WhatsApp integration.',
    image: '',
    comingSoon: true,
    tags: ['Astro', 'TypeScript', 'Netlify', 'Freelance', 'OnGoing'],
    link: 'https://cigana-lila.netlify.app/',
    year: '2025',
  },
]

export const TIMELINE = [
  {
    id: 1,
    period: 'Nov 2025 — Present',
    company: 'Consir Informática',
    role: 'Frontend Engineer',
    desc: 'Liderança técnica na modernização de sistema legado de gestão sindical para Vue.js 3 + TypeScript. Implementação de arquitetura base store com Pinia e PWA.',
    tags: ['Vue 3', 'TypeScript', 'Pinia', 'PWA'],
  },
  {
    id: 2,
    period: 'Jul 2025 — Nov 2025',
    company: 'Consir Informática',
    role: 'Pleno Frontend Engineer',
    desc: 'Engenharia de sistemas corporativos escaláveis focada em Vue.js, TypeScript e manutenção de alto nível.',
    tags: ['Vue.js', 'TypeScript', 'Enterprise'],
  },
  {
    id: 3,
    period: 'Jan 2025 — Jul 2025',
    company: 'Freelance Specialist',
    role: 'Frontend Consultant',
    desc: 'Liderança técnica em projetos de alto impacto (Itu Pneus, RvOne, Cajuscript) com foco em conversão e performance.',
    tags: ['Next.js 15', 'SEO', 'Consultancy'],
  },
  {
    id: 4,
    period: 'Oct 2021 — Dec 2024',
    company: 'Labi9 Tecnologia',
    role: 'Frontend Developer',
    desc: '3+ anos em ecossistema de fintechs. Desenvolvimento de interfaces complexas com React, Qwik e Nuxt.',
    tags: ['React', 'Nuxt', 'Fintech'],
  },
  {
    id: 5,
    period: '2019',
    company: 'SIALOG Software',
    role: 'Tech Intern',
    desc: 'Fundamentos em Ruby on Rails e JasperReports para logística.',
    tags: ['Ruby on Rails', 'Git'],
  },
]

export const USER_PHOTO =
  '/images/ricardo-camilo-programador-frontend-web-developer-frontend-engineer-software-engineer-web-developer-vuejs-vue-reactjs-react-javascript-typescript.png'
export const WHATSAPP_URL = 'https://wa.me/5514996765389'
